export const COLORS = {
  inputTextColor: '#141414',
  textColor: 'black',
  unlikeButtonColor: '#808080',
  buttonTextColor: '#ffffff',
  buttonColor: '#3849aa',
  screenHeaderBackground: '#00227b',
  fieldHeaderColor: '#3949ab',
  drawerActiveBackgroundColor: '#6e74dc',
  drawerActiveTintColor: '#3949ab',
  underConstructionTextColor: '#141414',
  formBackgroundColor: '#eeeeee',
  formInputAreaColor: '#f5f5f5',
  tabBackgroundColor: '#6f74dd',
};
