name: Web Bug Report
description: Report a bug on the website
title: "[Bug]: "
labels: ["Type: Bug", "Status: Available", "Priority: Medium", "Component: Frontend"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this bug!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please first explain the expected behaviour, then explain the current behaviour.
      placeholder: Expected Behaviour:... Current Behaviour:...
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Which version?
      description: Version of our software you are using
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Which browsers?
      description: Browsers you are experiencing the problem on
      multiple: true
      options:
        - Chrome
        - Opera  
        - Safari
        - Microsoft Edge
        - Firefox
  - type: textarea
    id: images
    attributes:
      label: Relevant screenshots
      description: Please copy and paste any relevant screenshots.
